version: "3.8"

services:
  backend:
    build: . # Builds from the Dockerfile in the current directory
    ports:
      - "7000:7000" # Exposes backend on port 7000
    restart: always # Restarts container if it crashes
    environment:
      - NODE_ENV=production
      - IMGUR_CLIENT_ID=your_client_id # Add your Imgur Client ID here
    depends_on:
      - mongo # If you're using MongoDB
    volumes:
      - ./src/public/avatars:/usr/src/server/src/public/avatars # Ensure avatar directory is persistent

  mongo:
    image: mongo:latest # MongoDB for user data storage
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db # Persist database data

volumes:
  mongo-data: # Volume for MongoDB data persistence
